### ISSUE TITLE
CoastSnap in trial version matlab 2020.

### ISSUE THREAD

**Issue by GermanMarchand** [Coastal-Imaging-Research-Network/CoastSnap-Toolbox#1]
Good evening, I am trying to use Matlab 2020 with an available trial version.

I am having trouble getting it to work.
I copy pictures[Imágenes problema](https://docs.google.com/document/d/1Z61pyOHE7o2rOxATJEB7RCQ9KYJwMbia9XygU5NJBMs/edit?usp=drivesdk) .

**Comment by mitchharley** [comment]
Hi German,

Did you load the GUI by typing CSP into the command window? This error usually happens when you try to load the GUI by double-clicking on the CSP.fig file. 

You need to load the GUI by typing CSP into the command window

Regards,
Mitch
