### ISSUE TITLE
Error in rectification 

### ISSUE THREAD

**Issue by YannDarchen** [Coastal-Imaging-Research-Network/CoastSnap-Toolbox#12]
Hello, 

I was following the tutorial on youtube but i'm stuck  at the image rectification. 
I finished the 7 GCP and right after i got this error. 

![image](https://user-images.githubusercontent.com/56580897/206189808-cf1f9aae-b453-46b0-8e81-c6e7e24ef69b.png)

Can you help me ? 

Best regards, 
Yann

**Comment by mitchharley** [comment]
This looks like you dont have the most recent version of the CoastSnapDB.xlsx file. You should be able to see the fields Min FOV and Max FOV under Rectification Settings. If not, please update to the latest
 
![image](https://user-images.githubusercontent.com/16750957/231182128-4e2f3c8b-330b-4197-80df-ed10e3a97394.png)
