### ISSUE TITLE
Error in Image Processing

### ISSUE THREAD

**Issue by BessCRC** [Coastal-Imaging-Research-Network/CoastSnap-Toolbox#13]
The images I am trying to process are not being assigned the correct date, with some even wanting to be placed in years such as 2024 or 3035. I have not changed the date formatting used in the DB. What can I do to correct this?

**Comment by mitchharley** [comment]
HI @BessCRC Can you please provide more details? Is this happening after you are running CSPraw2Processed? It could be that your "Default Timezone Offset From GMT" in the CoastSnapDB is wrong? It should be a number between -12 and 12

**Comment by BessCRC** [comment]
This is happening after running CSPraw2Processed. I've tried using CSPraw2ProcessedNoDB instead, but that doesn't work either. My default timezone offset is EST, which is set to -5. I've included pictures of the error messages I've been getting.
    On Friday, June 16, 2023 at 02:20:24 AM EDT, mitchharley ***@***.***> wrote:  
 
 


HI @BessCRC Can you please provide more details? Is this happening after you are running CSPraw2Processed? It could be that your "Default Timezone Offset From GMT" in the CoastSnapDB is wrong? It should be a number between -12 and 12

**Comment by BessCRC** [comment]
Hi, I was able to figure out the error. There was a problem with how Excel was reading the dates.Thanks for your help!
    On Friday, June 16, 2023 at 02:20:24 AM EDT, mitchharley ***@***.***> wrote:  
 
 


HI @BessCRC Can you please provide more details? Is this happening after you are running CSPraw2Processed? It could be that your "Default Timezone Offset From GMT" in the CoastSnapDB is wrong? It should be a number between -12 and 12
