### ISSUE TITLE
CSPreadSiteDB.m

### ISSUE THREAD

**Issue by ritsa4** [Coastal-Imaging-Research-Network/CoastSnap-Toolbox#4]
Hi,

many thanks for this amazing work. Could you please update also the CoastSnapDB.xlsx file based on your last updates? (like FOV limits, gcp combo) Gives a lot of errors now and would be really helpful. 

Thanks a lot.

**Comment by mitchharley** [comment]
The latest CoastSnapDB.xlsx structure is found in the latest version of the CoastSnap Starter Kit (version 3). You can find the zip file here: https://tinyurl.com/CoastSnapWebinar2020
