### ISSUE TITLE
Variable 'geomplot'

### ISSUE THREAD

**Issue by fed1942** [Coastal-Imaging-Research-Network/CoastSnap-Toolbox#5]
I having problems when i run CSPtagRegisterdedImages (in both Matlab 2014 and 2020). The error i get is 'Unrecognized function or variable geomplot'.

**Comment by mitchharley** [comment]
geomplot is found in the tools folder on the Master tree (https://github.com/Coastal-Imaging-Research-Network/CoastSnap-Toolbox/tree/master/tools). If Matlab is not finding it, you need to run CSPsetPaths first (or put it in your startup)
