### ISSUE TITLE
Images loading upside down

### ISSUE THREAD

**Issue by samkrovetz** [Coastal-Imaging-Research-Network/CoastSnap-Toolbox#7]
For some reason when I load an image using the GUI the image loads upside down. It's only doing this for one site and not any others. The photo is not upside down in the file, but only shows up flipped in the Matlab GUI. Has anybody else had this problem?

**Comment by mitchharley** [comment]
@samkrovetz I have never encountered this issue sorry. It might be the way the image was taken and then edited?
