### ISSUE TITLE
Rectify Image -> Map Shoreline Error 

### ISSUE THREAD

**Issue by SiegmundN** [Coastal-Imaging-Research-Network/CoastSnap-Toolbox#9]
After selecting the different GCP, I get an error:

Index exceeds the number of array elements. Index must not exceed 0.
Error in CSPGrectifyImage (line 103)
    HFOV_min = siteDB.rect.FOVlims(1); %From DB

Is this something I have to change in the Database?

**Comment by sivaiahborra** [comment]
Dear All, 
I have created timex dark and bright images by using other sources, so now I am looking for how to extract shoreline from those, which portion of the code exactly do I need to use ? can someone let me know if anyone done this completely. Thank you

**Comment by mitchharley** [comment]
@SiegmundN It looks like you need to set your Min FOV and Max FOV in the Excel Database. Vales of 40 and 70 are reasonable for this.
![image](https://user-images.githubusercontent.com/16750957/139603033-8b293e5a-0f3b-45d7-b136-f8b94dd25191.png)

**Comment by mitchharley** [comment]
@sivaiahborra The shoreline mapping toolbox is what CoastSnap uses to map the shorelines. I wrote that too but decided to keep it separate from CoastSnap as it has more general applications

https://github.com/Coastal-Imaging-Research-Network/Shoreline-Mapping-Toolbox

**Comment by SiegmundN** [comment]
Thanks @mitchharley! The Min and Max FOV were indeed missing in the Excel Database.
The code is now working

**Comment by sivaiahborra** [comment]
> @sivaiahborra The shoreline mapping toolbox is what CoastSnap uses to map the shorelines. I wrote that too but decided to keep it separate from CoastSnap as it has more general applications
> 
> https://github.com/Coastal-Imaging-Research-Network/Shoreline-Mapping-Toolbox

Dear @mitchharley 
Thank you. What do I need before I start this toolbox I mean I have got timex, dark and bright images and pixel instruments like 1D x and y transects, 2D grid array of pixels. If are these enough, from where to start and end?
